---
title: "Penguins Lab"
author: "Daphne Virlar"
date: "11/7/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Load packages and read in penguin data

Packages: tidyverse, car, onewaytests
```{r}

library(tidyverse)
library(car)
library(onewaytests)

penguins <- read_csv("penguins.csv")

```


*Our question: Is there a significant difference in mean flipper lengths for female Chinstrap, Gentoo, and Adelie penguins near Palmer Archipelago?*

Maybe I can use a one-way ANOVA...
-Independent observations
-Equal Variance (levene's test)
-Normality (histograms / qqplot)


```{r, wrangle}

counts <- with(penguins, table(species, sex))
View(counts)

#Update the names of colummns to make data more manageable
penguins2 <- penguins %>% 
  mutate(
    common_name = 
      case_when(
        species == "Chinstrap penguin (Pygoscelis antarctica)" ~ "Chinstrap",
        species == "Gentoo penguin (Pygoscelis papua)" ~ "Gentoo",
        species == "Adelie Penguin (Pygoscelis adeliae)" ~ "Adelie"
      )
  ) %>% 
  select(-species) %>% 
  filter(sex == "FEMALE")



```



2. Wrangle some data!
```{r}



# Random Variable: Flipper length
# Number of Factors: 1
# No. of Levels: 3
# Factor: Species
# Levels: Chinstrap, Gentoo, and Adelie



```



